[package]
name = "strictly-data"
version = "0.1.0"
edition = "2018"
default-run = "generate"

[dependencies]
csv = "1.1"
html-escape = "0.2.9"
lol_html = "0.3.2"
reqwest = { version = "0.11.3", features = ["blocking"] }
serde = { version = "1", features = ["derive"] }
